# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class SipoppolicyItem(scrapy.Item):
    # ----------------------------这些是列表页的原装字段--------------------------
    # abandonedDocument = scrapy.Field()
    # area = scrapy.Field()
    # areaCode = scrapy.Field()
    # attachementFileName = scrapy.Field()
    # attachementOSSUrl = scrapy.Field()
    # attachmentId = scrapy.Field()
    # attachmentLocalUrl = scrapy.Field()
    # attachmentName = scrapy.Field()
    # city = scrapy.Field()
    # cityCode = scrapy.Field()
    # contentAttribute = scrapy.Field()
    # contentAttributeCode = scrapy.Field()
    # contentAttributeList = scrapy.Field()
    # createUserId = scrapy.Field()
    # createUserName = scrapy.Field()
    # fileOriginal = scrapy.Field()
    # fileRemark = scrapy.Field()
    # handleState = scrapy.Field()
    # 这个字段本来是 id , 但是会和内部的 id 冲突, 所以改为sipop_id
    sipop_id = scrapy.Field()
    # implementDept = scrapy.Field()
    # implementMode = scrapy.Field()
    # implementModeCode = scrapy.Field()
    # implementModeList = scrapy.Field()
    # implementationTime = scrapy.Field()
    # industry = scrapy.Field()
    # industryCode = scrapy.Field()
    # isHaveAttachment = scrapy.Field()
    # isHaveGraphic = scrapy.Field()
    # isHaveProjectDeclaration = scrapy.Field()
    # isHaveUnscramble = scrapy.Field()
    # isRefuse = scrapy.Field()
    # justiceInterpretPolicyId = scrapy.Field()
    # justiceInterpretPolicyName = scrapy.Field()
    # lastModifiedTime = scrapy.Field()
    # maximumFunding = scrapy.Field()
    # organization = scrapy.Field()
    # organizationAddress = scrapy.Field()
    # organizationList = scrapy.Field()
    # organizationTelephone = scrapy.Field()
    # originalLastWebSite = scrapy.Field()
    # originalWebsite = scrapy.Field()
    # policyCRIList = scrapy.Field()
    policyId = scrapy.Field()
    # policyName = scrapy.Field()
    # policyType = scrapy.Field()
    # policyTypeCode = scrapy.Field()
    # policyTypeName = scrapy.Field()
    # province = scrapy.Field()
    # provinceCode = scrapy.Field()
    # publicNumber = scrapy.Field()
    # publishTime = scrapy.Field()
    # recipients = scrapy.Field()
    # recipientsCode = scrapy.Field()
    # recipientsList = scrapy.Field()
    # referenceFileName = scrapy.Field()
    # region = scrapy.Field()
    # remark = scrapy.Field()
    # revisedVersion = scrapy.Field()
    # scope = scrapy.Field()
    # stage = scrapy.Field()
    # technicalField = scrapy.Field()
    # validity = scrapy.Field()
    # validityCode = scrapy.Field()
    # validityDate = scrapy.Field()
    # validityName = scrapy.Field()
    # yfsj = scrapy.Field()
    # ---------------------------列表页字段完毕----------------------

    # ----------------------------详情页字段--------------------------
    abandonedDocument = scrapy.Field()
    area = scrapy.Field()
    areaCode = scrapy.Field()
    attachementFileName = scrapy.Field()
    attachementOSSUrl = scrapy.Field()
    attachmentId = scrapy.Field()
    attachmentLocalUrl = scrapy.Field()
    attachmentName = scrapy.Field()
    city = scrapy.Field()
    cityCode = scrapy.Field()
    contentAttribute = scrapy.Field()
    contentAttributeCode = scrapy.Field()
    # 没必要抓这个
    # contentAttributeList = scrapy.Field()
    createUserId = scrapy.Field()
    createUserName = scrapy.Field()
    fileOriginal = scrapy.Field()
    fileRemark = scrapy.Field()
    handleState = scrapy.Field()
    # sipop_id = scrapy.Field()
    implementDept = scrapy.Field()
    implementMode = scrapy.Field()
    implementModeCode = scrapy.Field()
    # 这个没必要抓
    # implementModeList = scrapy.Field()
    implementationTime = scrapy.Field()
    industry = scrapy.Field()
    industryCode = scrapy.Field()
    isHaveAttachment = scrapy.Field()
    isHaveGraphic = scrapy.Field()
    isHaveProjectDeclaration = scrapy.Field()
    isHaveUnscramble = scrapy.Field()
    isRefuse = scrapy.Field()
    justiceInterpretPolicyId = scrapy.Field()
    justiceInterpretPolicyName = scrapy.Field()
    lastModifiedTime = scrapy.Field()
    maximumFunding = scrapy.Field()
    organization = scrapy.Field()
    organizationAddress = scrapy.Field()
    # 没有必要抓
    # organizationList = scrapy.Field()
    organizationTelephone = scrapy.Field()
    originalLastWebSite = scrapy.Field()
    originalWebsite = scrapy.Field()
    policyCRIList = scrapy.Field()
    # policyId = scrapy.Field()
    policyName = scrapy.Field()
    policyType = scrapy.Field()
    policyTypeCode = scrapy.Field()
    policyTypeName = scrapy.Field()
    province = scrapy.Field()
    provinceCode = scrapy.Field()
    publicNumber = scrapy.Field()
    publishTime = scrapy.Field()
    recipients = scrapy.Field()
    recipientsCode = scrapy.Field()
    # 这个没必要吧
    # recipientsList = scrapy.Field()
    referenceFileName = scrapy.Field()
    region = scrapy.Field()
    remark = scrapy.Field()
    revisedVersion = scrapy.Field()
    scope = scrapy.Field()
    stage = scrapy.Field()
    technicalField = scrapy.Field()
    validity = scrapy.Field()
    validityCode = scrapy.Field()
    validityDate = scrapy.Field()
    validityName = scrapy.Field()
    yfsj = scrapy.Field()
